### ISSUE TITLE
gwf-core resources cannot currently be deployed in all regions

### ISSUE THREAD

**Issue by jennomics** [aws-samples/aws-genomics-workflows#117]
The core workflow can only be installed in US East (N. Virginia), US East (Ohio), US West (Oregon), Europe (Ireland), Europe (Frankfurt), and Asia Pacific (Singapore). Maybe this is noted somewhere, but I missed it.

gwfcore-batch.template.yaml includes r5n and m5n instance types, but those are only available in the above regions.

**Comment by wleepang** [comment]
For wider deployability, you could remove the *n instance types from the list for the compute environments. Important to note that the network optimized instances help with network contention when staging large datasets.

**Comment by brooksomics** [comment]
Since I'm on `us-west-1`, I reverted `IntanceTypes` back to `-optimal` as [was done previously](https://github.com/aws-samples/aws-genomics-workflows/commit/9c081ab2f347df6bc2a044defab37a38877c834e#diff-a932f1c4de3ad4e5aef9bd4db2bf9d1e01f237f57a06e7fd95215efb315e47c7).

My error:
```
Embedded stack arn:aws:cloudformation:us-west-1:448313343180:stack/gwfcore-IamStack-1VRT3Z6G4X86Q/034fc950-6a5f-11eb-abee-06313925a357 was not successfully created: The following resource(s) failed to create: [BatchServiceRole, BatchInstanceRole, BatchSpotFleetRole, BatchJobRole].
``` 

Despite explicitly assigning these Policies/Roles to the Stack in the Wizard setup, even though it's already in the yaml (e.g. [BatchServiceRole](https://github.com/aws-samples/aws-genomics-workflows/blob/0f22f146990533dfa8f03c88a85050fb4fc05fbe/src/templates/gwfcore/gwfcore-iam.template.yaml#L151-L162)), I can't get past the `IamStack` build. 

My goal is to setup `gwfcore` to use with NextFlow. I can run Batch/Spot jobs via NextFlow, but am having trouble getting through your [tutorial](https://docs.opendata.aws/genomics-workflows/orchestration/nextflow/nextflow-overview/).

**Comment by brooksomics** [comment]
Starting at the [VPC step](https://docs.opendata.aws/genomics-workflows/quick-start/) I was able to set up `gwfcore` in `us-east-1`, but it remains unclear to me if my original issue is a VPC issue with my `us-west-1` setup, an issue with me changing the template to `-optimal`, or some other permissions issue with my first setup.

**Comment by brooksomics** [comment]
I was pointing to the wrong place for `ArtifactBucketPrefix`. I thought this was referring to the `ecs-additions` directory in the repo, since the GUI description mentions additions. After leaving `ArtifactBucketName` = aws-genomics-workflows, `ArtifactBucketPrefix` = v3.0.4/artifacts, and pointing to `/templates` within our internal s3 (which included the *n removed instant type list), my issue was resolved.
