### ISSUE TITLE
How to specify ulimits

### ISSUE THREAD

**Issue by dfeinzeig** [aws-samples/aws-genomics-workflows#150]
What is the best way to set ulimits on the compute instances? I need higher limits for my docker image.

**Comment by wleepang** [comment]
@dfeinzeig - If you are working with AWS Batch directly, you can do this via the ContainerProperties in a Batch Job Definition:
https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html#containerProperties

Your mileage will vary if you are working with AWS Batch via an orchestration engine - it will depend on what parts of the AWS Batch API they expose. For example, while Nextflow doesn't do it directly (as far as I'm aware), you can indirectly by specifying a Job Definition ARN instead of a container image URI in a `process` that uses the `awsbatch` executor.

**Comment by wleepang** [comment]
If you need this on a per-container (per-task) basis within the WDL workflow you submit to Cromwell, it would likely need to be a `runtime` parameter set on the task that is then interpreted by the AWS Batch backend. I don't believe ulimits are wired up at the moment, but it should be relatively straightforward to add it.

@markjschreiber - can you comment more?

**Comment by henriqueribeiro** [comment]
Hey @dfeinzeig,

I just submitted a PR (https://github.com/broadinstitute/cromwell/pull/6204) with a draft version that enable the possibility to pass the `ulimits`.

**Comment by dfeinzeig** [comment]
Thx! I think that is just part of the issue. I needed to modify my launch templates in order to set higher limits and to update `/etc/sysconfig/docker` in order to remove the default ulimit restriction that docker runs with.

**Comment by henriqueribeiro** [comment]
Not sure if I understood correctly. With this change, when you define the `ulimits` they are passed directly to docker. You can see it here https://docs.aws.amazon.com/batch/latest/userguide/job_definition_parameters.html#containerProperties in the `ulimits`section.

**Comment by dfeinzeig** [comment]
By default the ECS host sets some limits on ulimits for the docker service. I had to update `/etc/sysconfig/docker` in the launch template to raise those limits.
