### ISSUE TITLE
same Nextflow container across several environments

### ISSUE THREAD

**Issue by JeffBurdine** [aws-samples/aws-genomics-workflows#176]
I have been using these templates for awhile and first I wanted to thank everyone for their contributions.
My question is do you think it would make sense to change the image name of the nextflow container that is created to the namespace of when the templates are run.  
When I run these templates they are self contained and create all the resources required seperately with the exception of the actual nextflow container.  The issue here is if I want to run one environment with a different version of nextflow changing the "nextflow" container changes it for all the different environments as they all share the "nextflow" container.  Only one "nextflow" container is added to ECR rather then a seperate container for each run of the template.
Possibly I am missing an easy solution or just doing it incorrectly.

**Comment by genecentric** [comment]
So I may have found a good work around for me but rather than just deleting the question I will just leave it and the moderators can do what they want.  Initially I was just going to change the templates to name the container based on the namespace rather than just "nextflow"  but then I realized that it is nice to use the same container as when I want to apply a change like updating the nextflow version I can do it once and it will update all the batch environments at once.  If I want to change an individual environment I can use code commit and rebuild the container using "start build with overrides" and change the "IMAGE_NAME" environment variable so it creates a new container.  then just make a revision of the Batch Job description that is used for that queue to use the new head node nextflow container image.  This allows me to create a specific nextflow container with different settings if desired.  Please let me know your thoughts.

**Comment by wleepang** [comment]
This is a good idea. CodeCommit is part of these templates to help manage
environment specific customizations that don't necessarily need a full
redeployment like customizing the container image or updating provisioning
scripts. For the container builds common practice is to keep the image name
close to the tool they wrap and use the image tag to signify any specific
versions or customizations.

That said, I'm curious what configuration options you would want to
specifically build into the container. The provided container entrypoint
allows for any command line arguments (e.g. -resume or -with-tower) to be
passed in via the Batch job command override.

**Comment by genecentric** [comment]
The only configurations I have changed so far are the following.
1. Adding SCM file environment variable for GitLab SCM authentication as detailed here.
https://github.com/aws-samples/aws-genomics-workflows/issues/145
2. Added to preserve session function in nextflow.aws.sh to output nextflow -with-report files if created similar to the nextflow session log files with GUID
 if [ -d .report ]; then
        echo "== copy nextflow reports =="
        aws s3 sync --no-progress .report $NF_LOGSDIR/.nextflow.report.${GUID/\//.}
    fi
Other than that I could imagine a use case for needing different versions of nextflow for different environments.  I can't think of any other head node container changes at the moment but just planning for the future.
