### ISSUE TITLE
artifacts

### ISSUE THREAD

**Issue by Parul-Kudtarkar** [aws-samples/aws-genomics-workflows#41]
@wleepang what is the purpose of artifacts i.e.

#!/bin/bash

CWD=`pwd`
ARTIFACT_PATH=${CWD}/artifacts
SOURCE_PATH=${CWD}/src

if [ ! -d ${ARTIFACT_PATH} ];
then
    mkdir ${ARTIFACT_PATH}
fi

if [ -f ${ARTIFACT_PATH}/aws-ebs-autoscale.tgz ];
then
    echo "asset [ebs-autoscale]: removing previous build:"
    rm -v ${ARTIFACT_PATH}/aws-ebs-autoscale.tgz
fi

if [ -f ${ARTIFACT_PATH}/aws-ecs-additions.tgz ];
then
    echo "asset [ecs-aditions]: removing previous build:"
    rm -v ${ARTIFACT_PATH}/aws-ecs-additions.tgz
fi

echo "repackaging:"
cd ${SOURCE_PATH}
tar -czvf ${ARTIFACT_PATH}/aws-ebs-autoscale.tgz ./ebs-autoscale/
tar -czvf ${ARTIFACT_PATH}/aws-ecs-additions.tgz ./ecs-additions/

cd ${CWD}

I am setting up an  example use case for our group that is based off your site code and cloud formation templates such that it is customized to our use case

**Comment by wleepang** [comment]
@Parul-Kudtarkar - Since this issue is closed, I presume you got the answer you needed?

For the record:
The artifacts are code/scripts/binaries that are either:

* required by all instances launched by AWS Batch (i.e. `aws-ebs-autoscale`)
* specific to workflow orchestration solutions (i.e. `aws-ecs-additions`)

These are best placed in an S3 bucket as they are used to bootstrap instances via an EC2 Launch Template.

**Comment by Parul-Kudtarkar** [comment]
@wleepang, yes I did. Thanks! Also, thanks for making the cloudformation templates available.
